---
# This playbook  deploys the mongodb configurationdb  servers

- name: Create data directory for mongoc configuration server
  ansible.builtin.file:
    path: "{{ mongodb_datadir_prefix }}/configdb"
    state: directory
    owner: mongod
    group: mongod

- name: Create the mongo configuration server startup file
  ansible.builtin.template:
    src: mongoc.j2
    dest: /etc/init.d/mongoc
    mode: "0655"

- name: Create the mongo configuration server file
  ansible.builtin.template:
    src: mongoc.conf.j2
    dest: /etc/mongoc.conf

- name: Copy the keyfile for authentication
  ansible.builtin.copy:
    src: roles/mongod/files/secret
    dest: "{{ mongodb_datadir_prefix }}/secret"
    owner: mongod
    group: mongod
    mode: "0400"

- name: Start the mongo configuration server service
  ansible.builtin.command:
    creates: /var/lock/subsys/mongoc
    cmd: /etc/init.d/mongoc start

- name: Pause
  ansible.builtin.pause:
    seconds: "20"

- name: Add the admin user
  community.mongodb.mongodb_user:
    name: admin
    database: admin
    password: "{{ mongo_admin_pass }}"
    login_port: "{{ mongoc_port }}"
    state: present
  ignore_errors: true
