---
- name: Install Java 1.7
  ansible.builtin.yum:
    name: java-1.7.0-openjdk
    state: present

- name: Add group "tomcat"
  ansible.builtin.group:
    name: tomcat

- name: Add user "tomcat"
  ansible.builtin.user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: false
  become: true

- name: Download & Extract Tomcat
  ansible.builtin.unarchive:
    src: http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz
    dest: /opt/
    owner: tomcat
    group: tomcat
    mode: u=rwX,g=rwX,o=rX
    remote_src: true

- name: Symlink install directory
  ansible.builtin.file:
    src: /opt/apache-tomcat-7.0.61
    path: /usr/share/tomcat
    state: link

- name: Change ownership of Tomcat installation
  ansible.builtin.file:
    path: /usr/share/tomcat/
    owner: tomcat
    group: tomcat
    state: directory
    recurse: true

- name: Configure Tomcat server
  ansible.builtin.template:
    src: server.xml.j2
    dest: /usr/share/tomcat/conf/
    owner: root
    group: tomcat
    mode: u=rw,g=r,o=r
  notify: restart tomcat

- name: Configure Tomcat users
  ansible.builtin.template:
    src: tomcat-users.xml.j2
    dest: /usr/share/tomcat/conf/
    owner: root
    group: tomcat
    mode: u=rw,g=r,o=r
  notify: restart tomcat

- name: Install Tomcat init script
  ansible.builtin.copy:
    src: tomcat-initscript.sh
    dest: /etc/init.d/tomcat
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Start Tomcat
  ansible.builtin.service:
    name: tomcat
    state: started
    enabled: true

- name: Deploy iptables rules
  ansible.builtin.template:
    src: iptables-save.j2
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: u=rw,g=,o=
  when:
    - ansible_os_family is match('RedHat')
    - ansible_distribution_major_version is version('6')
  notify: restart iptables

- name: Insert firewalld rule for tomcat http port
  ansible.posix.firewalld:
    port: "{{ http_port }}/tcp "
    permanent: true
    state: enabled
    immediate: true
  when:
    - ansible_os_family is match('RedHat')
    - ansible_distribution_major_version is version('7')

- name: Insert firewalld rule for tomcat https port
  ansible.posix.firewalld:
    port: "{{ https_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when:
    - ansible_os_family is match('RedHat')
    - ansible_distribution_major_version is version('7')

- name: Wait for tomcat to start
  ansible.builtin.wait_for:
    port: "{{ http_port }}"
