---
- name: Test Play
  hosts: all
  gather_facts: false
  connection: winrm
  vars:
    ansible_ssh_port : 5986
  
  tasks:
    - name:  Copy over wget
      win_copy:
        src: files/wget.exe
        dest: c:\

    - name: Run wget
      win_command: c:\wget.exe -q --read-timeout=0.0 --waitretry=5 --tries=400 --background http://freedns.afraid.org/dynamic/update.php?U1dFODUwTVRTTUlBQVNzTnpWSToxNjY0MjI2OA==
