---
- name: Test raw module
  hosts: all
  tasks:
    - name: Run ipconfig
      ansible.builtin.raw: ipconfig
      register: ipconfig
      changed_when: false

    - name: Print ipconfig
      ansible.builtin.debug:
        var: ipconfig

- name: Test stat module
  hosts: windows
  tasks:
    - name: Test stat module on file
      ansible.windows.win_stat:
        path: C:/Windows/win.ini
      register: stat_file

    - name: Print stat_file
      ansible.builtin.debug:
        var: stat_file

    - name: Check stat_file result
      ansible.builtin.assert:
        that:
          - stat_file.stat.exists
          - not stat_file.stat.isdir
          - stat_file.stat.size > 0
          - stat_file.stat.md5
