---
- name: Set service startup mode to auto and ensure it is started
  hosts: all
  gather_facts: false
  tasks:
    - name: Set Time Service
      win_service:
        name: "Windows Time"
        start_mode: auto
        state: started
