---
- name: Provision some instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - group_vars/all

  tasks:
    - name: Launch webserver instances
      amazon.aws.ec2_instance:
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        keypair: "{{ ec2_keypair }}"
        group: "{{ ec2_security_group }}"
        type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        region: "{{ ec2_region }}"
        instance_tags:
          ansible_group: "{{ ec2_tag_webservers }}"
          type: "{{ ec2_instance_type }}"
          group: "{{ ec2_security_group }}"
          Name: demo_{{ tower_user_name }}
        count: "{{ ec2_instance_count }}"
      register: ec2

    - name: Launch database instance
      amazon.aws.ec2_instance:
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        keypair: "{{ ec2_keypair }}"
        group: "{{ ec2_security_group }}"
        type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        region: "{{ ec2_region }}"
        instance_tags:
          ansible_group: "{{ ec2_tag_dbservers }}"
          type: "{{ ec2_instance_type }}"
          group: "{{ ec2_security_group }}"
          Name: demo_{{ tower_user_name }}
        count: "1"
      register: ec2

    - name: Launch load balancing instance
      amazon.aws.ec2_instance:
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        keypair: "{{ ec2_keypair }}"
        group: "{{ ec2_security_group }}"
        type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        region: "{{ ec2_region }}"
        instance_tags:
          ansible_group: "{{ ec2_tag_lbservers }}"
          type: "{{ ec2_instance_type }}"
          group: "{{ ec2_security_group }}"
          Name: demo_{{ tower_user_name }}
        count: "1"
      register: ec2

    - name: Launch monitoring instance
      amazon.aws.ec2_instance:
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        keypair: "{{ ec2_keypair }}"
        group: "{{ ec2_security_group }}"
        type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        region: "{{ ec2_region }}"
        instance_tags:
          ansible_group: "{{ ec2_tag_monitoring }}"
          type: "{{ ec2_instance_type }}"
          group: "{{ ec2_security_group }}"
          Name: demo_{{ tower_user_name }}
        count: "1"
      register: ec2

    - name: Wait for SSH to come up
      ansible.builtin.wait_for:
        host: "{{ item.public_dns_name }} "
        port: 22
        delay: 60
        timeout: 320
        state: started
      delegate_to: localhost
      with_items: "{{ ec2.instances }}"
