---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - { role: git, strategy: linear }
    - { role: mariadb }
    - { role: nginx }
    - { role: php-fpm }
    - { role: wordpress }
