---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - {role: common, tags: common}
    - {role: mariadb, tags: mariadb}
    - {role: nginx, tags: nginx}
    - {role: php-fpm, tags: php-fpm}
    - {role: wordpress, tags: wordpress}
