---
# this is an example of how to run repeated task elements over lists
# of items, for example, installing multiple packages or configuring
# multiple users

- hosts: all
  remote_user: root

  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: installed
      loop:
        - cobbler
        - httpd

    - name: Configure users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        groups: wheel
      loop:
        - testuser1
        - testuser2

    - name: Remove users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
      loop:
        - testuser1
        - testuser2

    - name: Copy templates
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: templates/testsource1
          dest: /example/dest1/test.conf
        - src: templates/testsource2
          dest: /example/dest2/test.conf
