---
#
# NetScaler module example
#

- hosts: web-pool
  serial: 3
  vars:
    nsc_host: nsc.example.com
    nsc_user: admin
    nsc_pass: nimda
    # type of the netscaler object you want to manipulate
    type: service
    # netscaler object name
    name: "{{ facter_fqdn }}:8080"

  tasks:
    - name: disable service in the lb
      community.network.netscaler_service:
        name: "{{ name }}"
        nsc_host: "{{ nsc_host }}"
        user: "{{ nsc_user }}"
        password: "{{ nsc_pass }}"
        type: "{{ type }}"
        action: disable

    - name: deploy new code
      ansible.builtin.command: yum upgrade -y

    - name: enable in the lb
      community.network.netscaler_service:
        name: "{{ name }}"
        nsc_host: "{{ nsc_host }}"
        user: "{{ nsc_user }}"
        password: "{{ nsc_pass }}"
        type: "{{ type }}"
        action: enable
