# this just shows some tricks possible with variables in Ansible 1.2 and later.

---
- hosts: all

  vars:
    a_list:
      - a
      - b
      - c

  tasks:
    - ansible.builtin.debug:
        msg: '"hello {{ ansible_hostname.upper() }}"'
    - ansible.builtin.command: echo match
      when: 2 == 2

    - ansible.builtin.command: echo no match
      when: 2 == 2 + 1

    - ansible.builtin.debug:
        msg: '"{{ ansible_os_family }}"'
    - ansible.builtin.command: echo {{ item }}
      with_items: a_list

    - ansible.builtin.command: echo 'RedHat'
      when: ansible_os_family == 'RedHat'
