---
##
# Example Ansible playbook that uses the Zfs module.
#
- name: Zfs
  hosts: webservers
  gather_facts: false
  become: true

  vars:
    pool: rpool

  tasks:
    - name: Create a zfs file system
      community.general.zfs:
        name: "{{ pool }}/var/log/httpd"
        state: present

    - name: Create a zfs file system with quota of 10GiB and visible snapdir
      community.general.zfs:
        name: "{{ pool }}/ansible"
        extra_zfs_properties:
          quota: 10M
          snapdir: enabled
        state: present

    - name: Create zfs snapshot of the above file system
      community.general.zfs:
        name: "{{ pool }}/ansible@mysnapshot"
        state: present

    - name: Create zfs volume named smallvol with a size of 10MiB
      community.general.zfs:
        name: "{{ pool }}/smallvol"
        extra_zfs_properties:
          volsize: 10M
        state: present

    - name: Removes snapshot of rpool/oldfs
      community.general.zfs:
        name: "{{ pool }}/oldfs@oldsnapshot"
        state: absent

    - name: Removes file system rpool/oldfs
      community.general.zfs:
        name: "{{ pool }}/oldfs"
        state: absent
