---
- name: Restart jboss
  ansible.builtin.service:
    name: jboss
    state: restarted
  listen: restart_jboss

- name: Restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted
  listen: restart_iptables
