[package]
name = "helloworld"
version = "0.1.0"
authors = ["Sviatoslav Sydorenko <wk+ansible-github@sydorenko.org.ua>", "Follpvosten <wolfi@karpador.xyz>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
