---
# this is an example to show that handlers can be included from yaml files,
# to promote reuse between different plays or even playbooks.  They work
# just like normal handlers.

- name: Restart apache
  ansible.builtin.service:
    name: httpd
    state: restarted
  listen: restart_apache

- name: Restart memcached
  ansible.builtin.service:
    name: memcached
    state: restarted
  listen: restart_memcached
