---
# Handlers for HAproxy

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  listen: restart_haproxy
- name: Reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded
  listen: reload_haproxy
