---
# This Playbook handles the addition of a web server to the pool.

- name: Add server to LB
  lineinfile: dest=/etc/haproxy/haproxy.cfg state=present regexp="${ansible_hostname}" line="server ${ansible_hostname} ${hostvars.{$inventory_hostname}.ansible_$iface.ipv4.address}:${httpd_port}"
  delegate_to: $item
  with_items: ${groups.lbservers}  
  register: last_run
   
- name: Reload the haproxy
  service: name=haproxy state=reloaded
  delegate_to: $item
  with_items: ${groups.lbservers} 
  only_if: ${last_run.changed}

