---
# This role will install MySQL and create db user and give permissions.

- name: Install Mysql package
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - MySQL-python

- name: Configure SELinux to start mysql on any port
  ansible.posix.seboolean:
    name: mysql_connect_any
    state: true
    persistent: true
  when: sestatus.rc != 0

- name: Create Mysql configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
    - restart_mysql

- name: Start Mysql Service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: Create Application Database
  community.mysql.mysql_db:
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  community.mysql.mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "*.*:ALL"
    host: "%"
    state: present
