---
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Deliver main configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify: restart_nginx

- name: Copy configuration file to nginx/sites-avaiable
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify: restart_nginx

- name: Make sure nginx start with boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
