---
# This playbook will install MariaDB and create db user and give permissions.
- name: Install MariaDB package
  ansible.builtin.yum:
    name: "{{ mariadb_packages }}"
    state: installed
  vars:
    mariadb_packages:
      - mariadb-server
      - MySQL-python
      - libselinux-python
      - libsemanage-python

- name: Configure SELinux to start mysql on any port
  ansible.posix.seboolean:
    name: mysql_connect_any
    state: true
    persistent: true

- name: Create Mysql configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: mysql
    mode: u=rw,g=r,o=r
  notify:
    - restart mariadb

- name: Create MariaDB log file
  ansible.builtin.file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: u=rwx,g=rwx,o=rx

- name: Start MariaDB Service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Insert firewalld rule
  ansible.posix.firewalld:
    port: "{{ mysql_port }}/tcp "
    permanent: true
    state: enabled
    immediate: true
