---
- name: ec2 
  hosts: localhost
  connection: local
  vars_files:
  - group_vars/all
  #gather_facts: False 
#i- hosts: localhost
  tasks:
   - name: launching AWS instance using Ansible
     ec2:
       key_name: "{{ ec2_key_name }}"
       instance_type: "{{ ec2_instance_type }}"
       image: "{{ ec2_image }}"
       region: "{{ ec2_region }}"
       wait: yes
       group_id: "{{ ec2_group_id }}"
       count: "{{ ec2_instance_count }}"
       vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
       assign_public_ip: yes
       aws_access_key:  "{{ ec2_access_key }}"  
       aws_secret_key: "{{ ec2_secret_key }}" 
       instance_tags:
          Name: "{{ ec2_instance_name }}"
