---
- name: Install OpenJDK
  ansible.builtin.yum:
    name: java-1.7.0-openjdk
    state: present

- name: Install Tomcat
  ansible.builtin.yum:
    name: tomcat
    state: present

- name: Deliver configuration files for tomcat
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: tomcat
    mode: u=rwX,g=rX,o=rX
    backup: true
  with_items:
    - { src: default.j2, dest: /etc/tomcat/default }
    - { src: server.xml.j2, dest: /etc/tomcat/server.xml }
    - { src: context.xml.j2, dest: /etc/tomcat/context.xml }
  notify: restart_tomcat

- name: Deliver libraries support memcached
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /usr/share/tomcat/lib/
    owner: root
    group: tomcat
    mode: u=rwX,g=rX,o=rX
  with_items:
    - http://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager/1.8.0/memcached-session-manager-1.8.0.jar
    - http://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager-tc7/1.8.0/memcached-session-manager-tc7-1.8.0.jar
    - https://spymemcached.googlecode.com/files/spymemcached-2.10.2.jar

- name: Deploy sample app
  ansible.builtin.copy:
    src: msm-sample-webapp-1.0-SNAPSHOT.war
    dest: /var/lib/tomcat/webapps/ROOT.war
    owner: tomcat
    group: tomcat
    mode: u=rw,g=r,o=r

- name: Start tomcat service
  ansible.builtin.service:
    name: tomcat
    state: started
    enabled: true
