---
- name: Install php-fpm and deps
  ansible.builtin.yum:
    name: "{{"
    state: present
    cmd: item }}
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml

- name: Disable default pool
  ansible.builtin.command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  ansible.builtin.template:
    src: wordpress.conf
    dest: /etc/php-fpm.d/
    
  notify: restart php-fpm
