---
- name: Install php-fpm and deps
  ansible.builtin.yum:
    name: "{{ php_packages }}"
    state: present
  vars:
    php_packages:
      - php
      - php-fpm
      - php-enchant
      - php-IDNA_Convert
      - php-mbstring
      - php-mysql
      - php-PHPMailer
      - php-process
      - php-simplepie
      - php-xml

- name: Disable default pool
  ansible.builtin.copy:
    src: /etc/php-fpm.d/www.conf
    dest: /etc/php-fpm.d/www.disabled
    remote_src: true
    owner: root
    group: nginx
    mode: u=rw,g=r,o=r
  notify: restart php-fpm

- name: Copy php-fpm configuration
  ansible.builtin.template:
    src: wordpress.conf.j2
    dest: /etc/php-fpm.d/
    owner: root
    group: nginx
    mode: u=rw,g=r,o=r
  notify: restart php-fpm
