---
- name: Add group "wordpress"
  ansible.builtin.group:
    name: wordpress

- name: Add user "wordpress"
  ansible.builtin.user:
    name: wordpress
    group: wordpress
    home: /srv/wordpress/

- name: Download & Extract WordPress
  ansible.builtin.unarchive:
    src: "http://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: /srv/wordpress
    owner: wordpress
    group: wordpress
    mode: u=rwX,g=rwX,o=rX
    remote_src: true

- name: Fetch random salts for WordPress config
  ansible.builtin.uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
  delegate_to: localhost
  register: wp_salt
  become: false

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    state: present

- name: Copy WordPress config file
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /srv/wordpress/
    owner: wordpress
    group: wordpress
    mode: u=r,g=r,o=

- name: Change ownership of WordPress installation
  ansible.builtin.file:
    path: /srv/wordpress/
    owner: wordpress
    group: wordpress
    state: directory
    recurse: true

- name: Install SEManage
  ansible.builtin.yum:
    pkg: policycoreutils-python
    state: present

- name: Set the SELinux policy for the Wordpress directory
  community.general.sefcontext:
    target: '/srv/wordpress(/.*)?'
    setype: httpd_sys_content_t
    state: present

- name: Set the SELinux policy for wp-config.php
  community.general.sefcontext:
    target: '/srv/wordpress/wp-config\.php'
    setype: httpd_sys_script_exec_t
    state: present

- name: Set the SELinux policy for wp-content directory
  community.general.sefcontext:
    target: '/srv/wordpress/wp-content(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Set the SELinux policy for the *.php files
  community.general.sefcontext:
    target: '/srv/wordpress/.*\.php'
    setype: httpd_sys_script_exec_t
    state: present

- name: Set the SELinux policy for the Upgrade directory
  community.general.sefcontext:
    target: "/srv/wordpress/wp-content/upgrade(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present

- name: Set the SELinux policy for the Uploads directory
  community.general.sefcontext:
    target: "/srv/wordpress/wp-content/uploads(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present

- name: Set the SELinux policy for the wp-includes php files
  community.general.sefcontext:
    target: '/srv/wordpress/wp-includes/.*\.php'
    setype: httpd_sys_script_exec_t
    state: present

- name: Set the SELinux on all the Files
  ansible.builtin.command: restorecon -Rv /srv/wordpress # noqa no-changed-when

- name: Start php-fpm Service
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: true
