---
# This playbook deploys the whole application stack in this site.

  
- name: apply common configuration to all nodes
  hosts: all
  remote_user: ec2-user

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: tag_Name_Webserver
  remote_user: ec2-user

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: tag_Name_Dbserver
  remote_user: ec2-user
 
  roles:
    - db
