---
# This playbook removes a webserver from the pool serially.
# Change the value of serial: to adjust the number of servers
# to be removed at a time.

- hosts: webservers
  user: root
  serial: 1
  tasks:
   - include: ../roles/web/tasks/remove_from_lb.yml
