---
# Playbook for HBase Masters

- name: Change root to be 0775
  shell: su - hdfs -c "hdfs dfs -chown hdfs:hadoop /"; su - hdfs -c "hdfs dfs -chmod 0775 /"

- name: Prepare hdfs for hbase
  shell: creates=/usr/lib/hadoop/hbase.initialized su - hdfs -c "hdfs dfs -mkdir /hbase" ; su - hdfs -c "hdfs dfs -chown hbase /hbase"; touch /usr/lib/hadoop/hbase.initialized

- name: Install the hbase masters packages
  yum: name=${item} state=installed
  with_items: 
   - hbase
   - hbase-doc
   - hbase-master

- name: Copy the hbase configuration files
  template: src=roles/common/templates/hbase_conf/${item}.j2 dest=/etc/hbase/conf/${item}
  with_items:
    - hadoop-metrics.properties
    - hbase-policy.xml
    - log4j.properties
    - hbase-env.sh               
    - hbase-site.xml
    - regionservers
  notify: restart hbase master

- name: start hbase master
  service: name={{ item }} state=started
  with_items:
    - hbase-master
