---
# This role installs httpd

- name: Install http
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - php
    - php-mysql
    - git

- name: Configure SELinux to allow httpd to connect to remote database
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true
  when: sestatus.rc != 0

- name: Http service state
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
