---
# This playbook installs httpd

- name: Install http and php etc
  yum: name=$item state=installed
  with_items:
   - httpd
   - libsemanage-python
   - libselinux-python

- name: http service state
  service: name=httpd state=started enabled=yes
