---
# Handlers for common notifications

- name: Restart ntp
  ansible.builtin.service:
    name: ntpd
    state: restarted
  listen: restart_ntp

- name: Restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted
  listen: restart_iptables
