# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False
 

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: lrich-key
         region: us-east-1
         group_id: sg-ec606896
         instance_type: t2.micro
         image: ami-2051294a
         vpc_subnet_id: subnet-f0ab60a8
         assign_public_ip: yes
         wait: true
         instance_tags:
            Name: Demo
      register: ec2

    - name: Add all instances public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances
     
