---
# This Playbook runs all the common plays in the deployment

- name: Create the hosts file for all machines
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: Create the repository for 10Gen
  ansible.builtin.copy:
    src: 10gen.repo.j2
    dest: /etc/yum.repos.d/10gen.repo

- name: Create the EPEL Repository.
  ansible.builtin.copy:
    src: epel.repo.j2
    dest: /etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  ansible.builtin.copy:
    src: RPM-GPG-KEY-EPEL-6
    dest: /etc/pki/rpm-gpg

- name: Create the mongod user
  ansible.builtin.user:
    name: mongod
    comment: '"MongoD"'

- name: Create the data directory for the namenode metadata
  ansible.builtin.file:
    path: "{{ mongodb_datadir_prefix }}"
    owner: mongod
    group: mongod
    state: directory

- name: Install the mongodb package
  ansible.builtin.yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - libselinux-python
    - mongo-10gen
    - mongo-10gen-server
    - bc
    - python-pip

- name: Install the latest pymongo package
  ansible.builtin.pip:
    name: pymongo
    state: latest # noqa package-latest
    use_mirrors: false

- name: Create the iptables file
  ansible.builtin.template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
  notify: restart_iptables
