---
- name: Copy operation
  ansible.builtin.copy:
    src: foo.txt
    dest: /tmp/roles_test1.txt

- name: Template operation
  ansible.builtin.template:
    src: foo.j2
    dest: /tmp/roles_test2.txt
  notify:
    - blippy

- name: Demo that parameterized roles work
  ansible.builtin.command: echo just FYI, param1={{ param1 }}, param2 ={{ param2 }}
