---
#This Playbook configures the mongos service of mongodb

- name: Create the mongos startup file
  ansible.builtin.template:
    src: mongos.j2
    dest: /etc/init.d/mongos
    mode: "0655"

- name: Create the mongos configuration file
  ansible.builtin.template:
    src: mongos.conf.j2
    dest: /etc/mongos.conf

- name: Copy the keyfile for authentication
  ansible.builtin.copy:
    src: roles/mongod/files/secret
    dest: "{{ mongodb_datadir_prefix }}/secret"
    owner: mongod
    group: mongod
    mode: "0400"

- name: Start the mongos service
  ansible.builtin.command:
    creates: /var/lock/subsys/mongos
    cmd: /etc/init.d/mongos start

- name: Pause
  ansible.builtin.pause:
    seconds: "20"

- name: Copy the file for shard test
  ansible.builtin.template:
    src: testsharding.j2
    dest: /tmp/testsharding.js

- name: Copy the file enable  sharding
  ansible.builtin.template:
    src: enablesharding.j2
    dest: /tmp/enablesharding.js

