---
# Create a new VM on an ESX server
# Returns changed = False when the VM already exists
# Returns changed = True and a adds ansible_facts from the new VM
# State will set the power status of a guest upon creation. Use powered_on to create and boot.
# Options ['state', 'vm_extra_config', 'vm_disk', 'vm_nic', 'vm_hardware', 'esxi'] are required together
- name: launch instances
  hosts: localhost
  connection: local
  gather_facts: False
 
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      #hostname: "{{ vsphere_host }}"
      #username: administrator@vsphere.local
      #password: vmware
      validate_certs: no
      #folder: /testvms
      name: "{{ vm_name }}-{{ 100 |random(start=1, step=1) }}"
      state: poweredon
      cluster: Cluster
      #template: "New RHEL 7.3"
      template: "RHEL 7.3 Template"
      datacenter: Datacenter
      disk:
      - size_gb: 20
        type: thin
        datastore: datastore1
      customization:
        name: "testvm"
        domain: "mod.local"
      hardware:
        memory_mb: 1024
        num_cpus: 1
        scsi: paravirtual
      #nic:
      #  - type: vmxnet3
      #    network: "VM Network"
      networks:
      - name: "VM Network"
        device_type: vmxnet3
        type: dhcp
        ip: "192.168.2.225"
        netmask: "255.255.0.0"
        #mac: aa:bb:dd:aa:00:14
      wait_for_ip_address: yes
    #delegate_to: localhost
    register: deploy



