---
- name: Download and install EPEL for Centos/RHEL version 6
  ansible.builtin.yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present
  when:
    - ansible_os_family is match('RedHat')
    - ansible_distribution_major_version is version('6')

- name: Download and install EPEL for Centos/RHEL version 7
  ansible.builtin.yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when:
    - ansible_os_family is match('RedHat')
    - ansible_distribution_major_version is version('7')

- name: Install libselinux-python
  ansible.builtin.yum:
    name: libselinux-python
    state: present
