---
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Copy nginx configuration for wordpress
  ansible.builtin.template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: nginx
    group: nginx
    mode: u=rwX,g=rwX,o=rX
  notify: restart_nginx

- name: Insert firewalld rule for nginx
  ansible.posix.firewalld:
    port: "{{ nginx_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: Http service state
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
