
- name: Configure Jenkins server
  hosts: "{{ hosts_list }}"
  remote_user: ec2-user
  tasks:
    - name: install git only if it is not already installed
      yum:
        name=git
        state=present

  roles:
    - geerlingguy.jenkins
    
  
