---
- name: Install memcached
  ansible.builtin.yum:
    name: memcached
    state: present

- name: Deliver configuration file
  ansible.builtin.template:
    src: memcached.conf.j2
    dest: /etc/sysconfig/memcached
    backup: true
    owner: root
    group: memcache
    mode: u=rw,g=r,o=
  notify: restart_memcached

- name: Deliver init script
  ansible.builtin.template:
    src: init.sh.j2
    dest: /etc/init.d/memcached
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  notify: restart_memcached

- name: Start memcached service
  ansible.builtin.service:
    name: memcached
    state: started
    enabled: true
