---
# This role contains common plays that will run on all nodes.

- name: Install python bindings for SE Linux
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present

  loop:
    - libselinux-python
    - libsemanage-python

- name: Create the repository for EPEL
  ansible.builtin.copy:
    src: epel.repo
    dest: /etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  ansible.builtin.copy:
    src: RPM-GPG-KEY-EPEL-6
    dest: /etc/pki/rpm-gpg

- name: Install some useful nagios plugins
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - nagios-nrpe
    - nagios-plugins-swap
    - nagios-plugins-users
    - nagios-plugins-procs
    - nagios-plugins-load
    - nagios-plugins-disk

- name: Install ntp
  ansible.builtin.yum:
    name: ntp
    state: present

  tags: ntp

- name: Configure ntp file
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: true

  tags: ntp

# work around RHEL 7, for now
- name: Insert iptables template
  ansible.builtin.template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables

  when: ansible_distribution_major_version != '7'
  notify: restart iptables

- name: Test to see if selinux is running
  ansible.builtin.command: getenforce
  register: sestatus
  changed_when: false
