---
# This will install nagios

- name: Install nagios
  ansible.builtin.yum:
    pkg: "{{ item }}"
    state: present
  loop:
    - nagios
    - nagios-plugins
    - nagios-plugins-nrpe
    - nagios-plugins-ping
    - nagios-plugins-ssh
    - nagios-plugins-http
    - nagios-plugins-mysql
    - nagios-devel
  notify: restart_httpd

- name: Create nagios config dir
  ansible.builtin.file:
    path: /etc/nagios/ansible-managed
    state: directory

- name: Configure nagios
  ansible.builtin.copy:
    src: nagios.cfg
    dest: /etc/nagios/nagios.cfg
  notify: restart_nagios

- name: Configure localhost monitoring
  ansible.builtin.copy:
    src: localhost.cfg
    dest: /etc/nagios/objects/localhost.cfg
  notify: restart_nagios

- name: Configure nagios services
  ansible.builtin.copy:
    src: ansible-managed-services.cfg
    dest: /etc/nagios/

- name: Create the nagios object files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/nagios/ansible-managed/
  loop:
    - webservers.cfg
    - dbservers.cfg
    - lbservers.cfg
  notify: restart_nagios

- name: Start nagios
  ansible.builtin.service:
    name: nagios
    state: started
    enabled: true
