---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - mariadb-server
      - MySQL-python

- name: Configure SELinux to start mysql on any port
  ansible.posix.seboolean:
    name: mysql_connect_any
    state: true
    persistent: true

- name: Create Mysql configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
    - restart_mariadb

- name: Create MariaDB log file
  ansible.builtin.file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: "0775"

- name: Create MariaDB PID directory
  ansible.builtin.file:
    path: /var/run/mysqld
    state: directory
    owner: mysql
    group: mysql
    mode: "0775"

- name: Start MariaDB Service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Insert firewalld rule
  ansible.posix.firewalld:
    port: "{{ mysql_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: Create Application Database
  community.mysql.mysql_db:
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  community.mysql.mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }} "
    priv: "*.*:ALL"
    host: "'%'"
    state: present

