---
## This playbook deploys the whole application stack in this site.

- name: Configure and deploy database servers
  hosts: tag_ansible_group_windows_dbservers
  connection: winrm
  vars:
    ansible_ssh_port: 5986

  roles:
    - mssql

  tags:
    - db

# Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- name: Configure and deploy the web servers
  hosts: tag_ansible_group_windows_webservers
  connection: winrm
  vars:
    ansible_ssh_port: 5986

  roles:
    - iis
    - web

  tags:
    - web

- name: Configure and deploy the load balancer(s)
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - elb

  tags:
    - lb

- name: Add the webservers to the load balancer(s)
  hosts: tag_ansible_group_windows_webservers
  connection: winrm
  gather_facts: false

  vars:
    ansible_ssh_port: 5986

  tasks:
    - name: Wait for webserver to come up
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 80
        state: started
        timeout: 80
      delegate_to: localhost

    - name: Add host to load balancing pool
      community.aws.elb_instance:
        region: us-east-1
        instance_id: "{{ ec2_id }}"
        ec2_elbs: ansible-windows-demo-lb
        wait_timeout: 330
        state: present

  tags:
    - lb
