---
# This playbook contains common plays that will be run on all nodes.

- name: Install chrony
  yum:
    name: chrony
    state: present
  tags: ntp

- name: Configure chrony file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service:
    name: chronyd
    state: started
    enabled: yes
  tags: ntp

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
